# Copyright (c) 2026, Neotec Integrated Solution and contributors
# For license information, please see license.txt
#
# Jinja helpers available inside Print Formats.
#
# Asset labels commonly build their QR in the browser, either with a JS library
# or by pointing an <img> at an external QR service. Neither works for
# server-side PDF output: the PDF engine may capture the page before scripts
# run, it needs outbound internet access to reach an external service, and an
# <img> with no src crashes Frappe's PDF pipeline outright. Generating the QR
# here removes all three problems, and works identically in browser preview.

import base64
import io

import frappe

# A short quiet zone. The QR spec asks for 4 modules, but label real estate is
# tight and 2 scans reliably at sticker sizes.
DEFAULT_BORDER = 2


def qr_backend():
    """Which QR backend is in use, and what it emits.

    The built-in encoder is preferred and always available - it needs nothing
    beyond the standard library, always encodes UTF-8, and always emits PNG.
    External libraries are kept only as a safety net.
    """
    try:
        from alphax_document_center import qrgen  # noqa: F401

        return "built-in (no dependencies)", "png"
    except Exception:
        pass
    try:
        import qrcode  # noqa: F401
        import PIL  # noqa: F401

        return "qrcode+Pillow", "png"
    except Exception:
        pass
    try:
        import pyqrcode  # noqa: F401
        import png  # noqa: F401

        return "pyqrcode+pypng", "png"
    except Exception:
        pass
    return None, None


def alphax_qr(text, border=DEFAULT_BORDER, box_size=10, ecc="L"):
    """Return a QR code for `text` as a PNG data URI, ready for an image source.

        <img class="qr" src="{{ alphax_qr(doc.name) }}">

    Generated by the app's own encoder, so it does not depend on any library
    being present on the bench. Always UTF-8, so Arabic asset names work, and
    always PNG, because wkhtmltopdf cannot render an SVG data URI.
    """
    if text is None or text == "":
        return ""

    failures = []
    text = frappe.utils.cstr(text)
    border = frappe.utils.cint(border) or DEFAULT_BORDER
    box_size = frappe.utils.cint(box_size) or 10
    ecc = (ecc or "L").upper()

    # 1. Built-in encoder. No dependencies, so this is the path that runs.
    try:
        from alphax_document_center import qrgen

        png = qrgen.png_bytes(text, level=ecc, scale=max(4, box_size // 2), border=border)
        return "data:image/png;base64," + base64.b64encode(png).decode()
    except Exception as exc:
        failures.append(f"built-in: {type(exc).__name__}: {exc}")

    # 2. qrcode + Pillow, if the payload somehow exceeds the built-in range.
    try:
        import qrcode

        levels = {
            "L": qrcode.constants.ERROR_CORRECT_L,
            "M": qrcode.constants.ERROR_CORRECT_M,
            "Q": qrcode.constants.ERROR_CORRECT_Q,
            "H": qrcode.constants.ERROR_CORRECT_H,
        }
        qr = qrcode.QRCode(
            error_correction=levels.get(ecc, qrcode.constants.ERROR_CORRECT_L),
            box_size=box_size,
            border=border,
        )
        qr.add_data(text)
        qr.make(fit=True)
        buf = io.BytesIO()
        qr.make_image(fill_color="black", back_color="white").save(buf, format="PNG")
        return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()
    except Exception as exc:
        failures.append(f"qrcode+Pillow: {type(exc).__name__}: {exc}")

    # 3. pyqrcode + pypng. encoding="utf-8" is mandatory - it defaults to
    #    latin-1 and raises on Arabic.
    try:
        import pyqrcode

        buf = io.BytesIO()
        pyqrcode.create(text, error=ecc.lower(), encoding="utf-8").png(
            buf, scale=max(4, box_size // 2), quiet_zone=border
        )
        return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()
    except Exception as exc:
        failures.append(f"pyqrcode+pypng: {type(exc).__name__}: {exc}")

    frappe.log_error(
        title="alphax_qr: could not generate a QR code",
        message="Every backend failed for this text.\n\n" + "\n".join(failures),
    )
    try:
        frappe.flags.alphax_qr_failures = failures
    except Exception:
        pass
    return ""


def alphax_asset_payload(doc, desc_limit=40):
    """The text encoded in an asset label QR.

    Mirrors the payload the browser-side label script produced, so existing
    tagged assets keep scanning to the same value:

        Asset ID: IRS-FNT-17-002
        Name: <asset or item name>
        Desc: <truncated description>
    """
    def field(*names):
        for n in names:
            value = doc.get(n) if hasattr(doc, "get") else getattr(doc, n, None)
            if value:
                return frappe.utils.cstr(value).replace("\r\n", " ").replace("\n", " ").strip()
        return ""

    code = field("name")
    name = field("asset_name", "item_name")
    desc = field("custom_asset_description", "description")
    if desc_limit and len(desc) > desc_limit:
        desc = desc[:desc_limit] + "..."

    parts = []
    if code:
        parts.append(f"Asset ID: {code}")
    if name:
        parts.append(f"Name: {name}")
    if desc:
        parts.append(f"Desc: {desc}")
    return "\n".join(parts) if parts else "N/A"


def alphax_asset_qr(doc, border=DEFAULT_BORDER, desc_limit=40):
    """QR code for an asset label, as a data URI.

        <img class="qr" src="{{ alphax_asset_qr(doc) }}">
    """
    return alphax_qr(alphax_asset_payload(doc, desc_limit=desc_limit), border=border)
